---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.assume_role }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry }}/{{ .Values.name }}:{{ .Values.rev }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 512Gi
          ports:
            - containerPort: 8083
          env:
            - name: FORCE_UPDATE
              value: "{{ .Values.force_update | default 0 }}"
            - name: DPF_SETTINGS
              value: "/data/.settings.json"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.aws_region | default "us-west-2" }}"
          volumeMounts:
            - name: settings-secrets
              mountPath: "/data"
              readOnly: true
      volumes:
        - name: settings-secrets
          secret:
            secretName: dino-park-fossil
